### ISSUE TITLE
请问作者，人邮教育出版社的资源可以写一个这样的脚本吗

### ISSUE THREAD

**Issue by AidienQ** [yanyaoli/cmpedu-dl#1]
人邮教育网的部分资源认证教师可以下载，部分资源教师也下载不了，说是核心版权，如果可以的话，麻烦作者试试能否写一个脚本。
![Snipaste_2024-04-01_22-42-10](https://github.com/yanyaoli/cmpedu-downloader/assets/90374310/5b9f98a1-47d1-41a7-b8e8-357d98bf4513)

**Comment by yanyaoli** [comment]
抱歉实现不了
